O7 door opens on unlock. Fixes #80.
UMDLARS/one_night_in_sf pull request #92
Opened 2023-01-05 20:22 UTC by pahp

I used the code for Office1Door as a template.

2023-01-06 09:22 UTC, spacehobo requested changes
I think we should avoid putting lock/unlock logic in rooms, because they intercept too many commands.  See inline comments for specifics.

2023-01-06 09:22 UTC, spacehobo commented on untitledHeistGame.inf
> +		give Office7Door open;
This logic feels like it really belongs in the `Office7Door` object's `before`/`after` routines.  Then you could `give self open;` and it would feel more contained.   Putting it in the room means that the following can happen:

```
(Hallway7)
This is a hallway. To the north the hallway extends. To the south there is the waiting area.
To the west there is an office.

You can see a Office Door here.

> i
You're carrying a loose brass key and a Task List.

> lock list with key
You carefully lock the office door with the brass key.
```

2023-01-06 09:24 UTC, spacehobo commented on untitledHeistGame.inf
> +		give Office7Door open;
Also note that you're just saying the door is locked without actually locking it.  Either you want to put this text in the after routine, or you want to copy the core logic and check to see if the player has the right key etc.

2023-01-06 09:26 UTC, spacehobo commented
If we're doing this in other hallways, we should probably generalise the fix, as well.

2023-01-06 22:16 UTC, pahp commented
@spacehobo how about this? And I agree about generalization; Hallway1 definitely needs to be fixed. Another benefit of this fix is that it works bidirectionally -- you get the same messages on either side of the door.

2023-01-07 22:12 UTC, spacehobo approved these changes
Seems legit.

2023-01-07 22:12 UTC, spacehobo commented on untitledHeistGame.inf
> +		give self open ~locked;
Since this is an `After`, you don't need to give `~locked`: the main `DoUnlockSub` will have taken care of that.  This is literally the "after the door is unlocked" routine.  Still, it's harmless so I'll merge this now.

2023-01-07 22:20 UTC, merged